# Generated by Django 2.2.7 on 2019-11-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EggGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_relative_link', models.CharField(max_length=500)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('national_dex', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('japanese_name', models.CharField(max_length=20)),
                ('japanese_transliteration', models.CharField(max_length=50)),
                ('japanese_romanized', models.CharField(max_length=50)),
                ('image_relative_link', models.CharField(max_length=500)),
                ('has_mega', models.BooleanField()),
                ('category', models.CharField(max_length=20)),
                ('hatch_time', models.IntegerField()),
                ('experience_yield', models.IntegerField()),
                ('gender_code', models.DecimalField(decimal_places=4, max_digits=4)),
                ('catch_rate', models.IntegerField()),
                ('base_friendship', models.IntegerField()),
                ('url', models.URLField()),
                ('egg_groups', models.ManyToManyField(to='pokedex.EggGroup')),
                ('introduced_generation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Generation')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PokemonDex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regional_dex', models.IntegerField()),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regional_dex', to='pokedex.Pokemon')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Region')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='regional_numbers',
            field=models.ManyToManyField(related_name='pokemons', through='pokedex.PokemonDex', to='pokedex.Region'),
        ),
        migrations.CreateModel(
            name='MegaStonePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image_relative_link', models.CharField(max_length=500)),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mega_stones', to='pokedex.Pokemon')),
            ],
        ),
        migrations.CreateModel(
            name='FormType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('Primary', 'P'), ('Secondary', 'S')], max_length=2)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_types', to='pokedex.Form')),
                ('pokemon_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.PokemonType')),
            ],
        ),
        migrations.CreateModel(
            name='FormAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot', models.CharField(choices=[('First', 'F'), ('Second', 'S'), ('Hidden', 'H'), ('Mega', 'M')], max_length=2)),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokedex.Ability')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_ability', to='pokedex.Form')),
            ],
        ),
        migrations.AddField(
            model_name='form',
            name='abilities',
            field=models.ManyToManyField(related_name='forms', through='pokedex.FormAbility', to='pokedex.Ability'),
        ),
        migrations.AddField(
            model_name='form',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='pokedex.Pokemon'),
        ),
        migrations.AddField(
            model_name='form',
            name='types',
            field=models.ManyToManyField(related_name='forms', through='pokedex.FormType', to='pokedex.PokemonType'),
        ),
    ]
