# Generated by Django 3.0 on 2019-12-18 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='image_relative_link',
        ),
        migrations.AddField(
            model_name='form',
            name='sprite_relative_link',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='region',
            name='descriptor',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='formability',
            name='slot',
            field=models.CharField(choices=[('F', 'First'), ('S', 'Second'), ('H', 'Hidden'), ('M', 'Mega')], max_length=2),
        ),
        migrations.AlterField(
            model_name='formtype',
            name='slot',
            field=models.CharField(choices=[('P', 'Primary'), ('S', 'Secondary')], max_length=2),
        ),
    ]
